modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
# issueTrackerURL=""

[[mods]]
modId="template"
version="0.0.1a"
displayName="Template" 
# updateJSONURL=""
# displayURL=""
# logoFile=""
authors="Willatendo"
description='''
'''

[[dependencies.template]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.template]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.template]]
    modId="simplelibrary"
    mandatory=true
    versionRange="[0.2.0,0.3.0)"
    ordering="NONE"
    side="BOTH"
    